### PR TITLE
Add development and CI configuration

### PR DESCRIPTION
**Pull request by hvelarde**
among other small fixes...

### CODE REVIEW

**Comment by vangheem** [comment]
Thanks @hvelarde

**Comment by hvelarde** [comment]
@vangheem I haven't finished :-)

tests are failing, do you know why?

**Comment by vangheem** [comment]
because there are no tests :)

**Comment by vangheem** [comment]
What can I say, I'm lazy. Annoying to mock http requests.

**Comment by hvelarde** [comment]
now you can implement them when you have time; CI is in place for Plone 4.2-5.0.

**Comment by vangheem** [comment]
well here, https://github.com/collective/wildcard.cloudflare/blob/master/wildcard/cloudflare/tests.py https://github.com/collective/wildcard.cloudflare/tree/master/wildcard/cloudflare/tests

conflicts in module definititions?

**Comment by vangheem** [comment]
there are like 3 tests: https://github.com/collective/wildcard.cloudflare/blob/master/wildcard/cloudflare/tests/test_urls.py

**Comment by vangheem** [comment]
but yes, thanks, next time I look at it, I'll try to update.

**Comment by hvelarde** [comment]
you can mock requests using [httmock](https://pypi.python.org/pypi/httmock); I used it in [collective.civicrm](https://github.com/collective/collective.civicrm/blob/master/src/collective/civicrm/tests/test_views.py)

**Pull request merged**
