### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by frapell** [comment]
@vangheem Would you like to review?

**Review by vangheem — APPROVED** [review]

**Comment by vangheem** [comment]
I don't use this anymore though! Someone at wildcard might want to take over maintenance? @zombified ?

**Comment by frapell** [comment]
@zombified Can we merge this and create a new release of this product?

**Comment by frapell** [comment]
@vangheem Do you have other means for contacting @zombified ? Unless it is ok if I would just merge this and create a new release (Dunno if I have the permissions to do so in pypi, though)

**Comment by vangheem** [comment]
Go ahead and merge. Or maybe just fork to collective namespace if no one is maintaining it? \cc @lucid-0

**Comment by frapell** [comment]
@vangheem You mean renaming the product? This is already in collective... I would only need permission to release in https://pypi.org/project/wildcard.cloudflare/

**Comment by lucid-0** [comment]
still here. haha not familiar with this specific product myself yet.

**Comment by zombified** [comment]
I can kick out another release, apologies.

**Comment by zombified** [comment]
release should be on pypi

**Comment by frapell** [comment]
@zombified Awesome! thanks :D

**Pull request merged**
